; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs=avr_example, esp32_example

; Default environment for the project
[env]
framework = arduino
monitor_speed = 115200

[env:esp32]
platform = espressif32
board = esp32-c3-devkitm-1
build_flags =
    -D DEBUG
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:nano]
platform = atmelavr
board = nanoatmega328

[env:example]
build_src_filter =
    +<../examples/*>
    +<*>
lib_deps =
    https://github.com/DanN91/platform-io-libraries#I2CDevice
    https://github.com/DanN91/platform-io-libraries#NonBlockingDelay
    https://github.com/DanN91/platform-io-libraries#ObserverPattern

[env:avr_example]
extends = env:nano, env:example

[env:esp32_example]
extends = env:esp32, env:example